const jwt = require('jsonwebtoken');
const env = require('../../config/environment');
const authRepository = require('./auth.repository');
const AppError = require('../../utils/AppError');

const login = async (username, password) => {
  // Demo mode: bypass DB entirely — no data from real tenants ever exposed
  if (username === 'demo') {
    if (password !== env.DEMO_PASSWORD) {
      throw new AppError('Credenciales incorrectas', 401);
    }
    const payload = {
      id: 0,
      username: 'demo',
      fullName: 'Usuario Demo',
      role: 'demo',
      tenants: [
        { id: 0,  name: 'Demo – Huevos Point' },
        { id: -1, name: 'Sucursal demo 2' },
      ],
    };
    const token = jwt.sign(payload, env.JWT_SECRET, { expiresIn: '4h' });
    return { token, user: payload };
  }

  const user = await authRepository.findByUsername(username);

  if (!user) {
    throw new AppError('Credenciales incorrectas', 401);
  }

  const isValidPassword = await user.validatePassword(password);

  if (!isValidPassword) {
    throw new AppError('Credenciales incorrectas', 401);
  }

  let userTenants = user.tenants || [];
  if (user.role === 'superadmin') {
    userTenants = await authRepository.findAllTenants();
  }

  const payload = {
    id: user.id,
    username: user.username,
    fullName: user.fullName,
    role: user.role,
    tenants: userTenants,
  };

  const token = jwt.sign(payload, env.JWT_SECRET, {
    expiresIn: env.JWT_EXPIRES_IN,
  });

  return { token, user: payload };
};

/**
 * Validates a JWT generated by Dashboard Maestro (cross-app auto-login).
 * The token must be signed with the same JWT_SECRET and carry _source: 'dashboard-maestro'.
 * Returns the decoded payload so the frontend can bootstrap a session with it.
 */
const autoLogin = (token) => {
  if (!token || typeof token !== 'string') {
    throw new AppError('Token requerido', 400);
  }

  let decoded;
  try {
    decoded = jwt.verify(token, env.JWT_SECRET);
  } catch {
    throw new AppError('Token inválido o expirado', 401);
  }

  if (decoded._source !== 'dashboard-maestro') {
    throw new AppError('Token no autorizado para auto-login', 403);
  }

  if (decoded.role !== 'superadmin') {
    throw new AppError('Solo superadmins pueden usar auto-login', 403);
  }

  return { token, user: decoded };
};

module.exports = { login, autoLogin };
